
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: Sample
// ---------------------------------------------

#include "Sample.h"

/*!
	@brief  Constructor for Sample
*/
Sample::Sample(){
    
}

/*!
	@brief  Destructor for Sample
*/
Sample::~Sample(){
    
}

/*!
	@brief  test
*/
void Sample::test(){
    //
}

/*!
	@brief  begin
*/
void Sample::begin(){
    // sample begin function, (not necessary)
    test();
}

/*!
	@brief  update
*/
void Sample::update(){
    // sample update function, (not necessary)
}

